# Generated by Django 2.2.7 on 2019-11-27 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoSoDaoTao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200)),
                ('diachi', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='LoaiVanBang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VanBang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoten', models.CharField(max_length=100)),
                ('ngaysinh', models.DateField()),
                ('gioitinh', models.CharField(choices=[('1', 'Men'), ('0', 'Female')], max_length=1)),
                ('cmnd', models.CharField(max_length=12)),
                ('ngaycapbang', models.DateField()),
                ('sohieu', models.CharField(max_length=100)),
                ('chuyennganh', models.CharField(max_length=100)),
                ('xeploai', models.CharField(choices=[('0', 'Kem'), ('1', 'Trung Binh'), ('2', 'Kha'), ('3', 'Gioi'), ('4', 'Xuat Xac')], max_length=1)),
                ('cosodaotao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapi.CoSoDaoTao')),
                ('loai_vanbang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapi.LoaiVanBang')),
            ],
            options={
                'ordering': ['ngaycapbang'],
                'unique_together': {('sohieu',)},
            },
        ),
    ]
