# Generated by Django 2.2.7 on 2019-11-28 01:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0002_auto_20191127_0627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vanbang',
            options={'ordering': ['ngaycapbang']},
        ),
        migrations.RemoveField(
            model_name='vanbang',
            name='namcapbang',
        ),
        migrations.AddField(
            model_name='vanbang',
            name='ngaycapbang',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
